### ISSUE TITLE
GB in infinite loop (?)

### ISSUE THREAD

**Issue by saschatimme** [ederc/GB.jl#2]
```julia
julia> using Singular, GB
julia> varnames = ["x$i" for i in 0:2]
3-element Array{String,1}:
 "x0"
 "x1"
 "x2"

julia> R, (x0, x1, x2,) = Singular.PolynomialRing(
                        Singular.QQ, varnames, ordering = :lex)
(Singular Polynomial Ring (QQ),(x0,x1,x2),(lp(3),C), spoly{n_Q}[x0, x1, x2])

julia> my_gens = [x0^3*x2^15+x0*x1*x2+x1^3+x2^12, x0^2*x2^9+x0*x1^2+x1*x2^3, x0^2*x1*x2^5+x0*x2^8+x1^2]
3-element Array{spoly{n_Q},1}:
 x0^3*x2^15+x0*x1*x2+x1^3+x2^12
 x0^2*x2^9+x0*x1^2+x1*x2^3     
 x0^2*x1*x2^5+x0*x2^8+x1^2     

julia> id = Singular.Ideal(R, my_gens)
Singular Ideal over Singular Polynomial Ring (QQ),(x0,x1,x2),(lp(3),C) with generators (x0^3*x2^15+x0*x1*x2+x1^3+x2^12, x0^2*x2^9+x0*x1^2+x1*x2^3, x0^2*x1*x2^5+x0*x2^8+x1^2)

julia> GB.f4(id) # doesn't seem to finish
```

**Comment by ederc** [comment]
There are several points to make here:

1. If you call GB.f4 with a lexicographically ordered system, you need to give GB.f4 at the moment the order as a parameter (monorder=:lex). Default is monorder=:degrevlex.

2. If you want to solve, you should compute the GB w.r.t. degrevlex order (way faster, under 0.01 seconds) and then convert the basis to a basis w.r.t. lex, e.g. using Singular's FGLM, etc. At the moment, we are working on implementing a conversion algorithm like FGLM directly in GB.

3. You should not directly compute over Q but use a multi modular approach. This is also under development at the moment. For your example, all the time spent in GB.f4 goes into gmp doing the arithmetic. Doing your example in finite characteristic the computation takes below 0.01 seconds (w.r.t. lex). Computing directly w.r.t. lex over Q it takes around 2 hours on my system.

**Comment by saschatimme** [comment]
Thank your for clarifying the points this was very instructive :)
