### ISSUE TITLE
Tag?

### ISSUE THREAD

**Issue by ChrisRackauckas** [ederc/GB.jl#41]
It would be good to get a tag on this so that StaticArrays 1 is allowed as a compat here.

**Comment by ChrisRackauckas** [comment]
Bump again?

**Comment by ederc** [comment]
Sorry, I have overlooked your issue so long since we had related issues in other projects I am working on right now. Tagging is done now.

**Comment by ChrisRackauckas** [comment]
I don't see the 0.3.3 tag in General: https://github.com/JuliaRegistries/General/pulls?q=is%3Apr+GroebnerBasis+is%3Aclosed

**Comment by ederc** [comment]
Should be there soon.

**Comment by ChrisRackauckas** [comment]
Thanks!
