### ISSUE TITLE
Random Error running GB.jl

### ISSUE THREAD

**Issue by iliailmer** [ederc/GB.jl#42]
Computation sometimes randomly terminates with an error saying:
```
__gmpn_addmul_1_coreisbr at /opt/hostedtoolcache/julia/1.6.2/x64/bin/../lib/julia/libgmp.so (unknown line)
```
I am not sure why it occurs in the first place, but it happens about 1 in 5 times of running the program

**Comment by ChrisRackauckas** [comment]
There might be an issue with Julia freeing the memory early?

**Comment by ederc** [comment]
@iliailmer Could you please provide me a minimal example for the above error?

**Comment by iliailmer** [comment]
@ederc I will close the issue, I think ever since v0.3.3 this no longer occurs.
