### ISSUE TITLE
Request to reuse package name

### ISSUE THREAD

**Issue by shashi** [ederc/GB.jl#44]
Hello!

Since this package is now deprecated, would you be willing to allow registering https://github.com/sumiya11/GroebnerBases in the General Julia registry under the name GroebnerBasis.jl?

It is a pure Julia implementation.

cc @sumiya11

**Comment by ederc** [comment]
Packages cannot be removed from the registry:
[https://github.com/JuliaRegistries/General#how-do-i-remove-a-package-or-version-from-the-registry](https://github.com/JuliaRegistries/General#how-do-i-remove-a-package-or-version-from-the-registry).

The package will be revived in the future with different algorithms and implementations.
